// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const upsertCompany = `-- name: UpsertCompany :one
INSERT INTO companies (name, name_normalized)
VALUES ($1::text, $2::text)
ON CONFLICT (name_normalized) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertCompanyParams struct {
	Name           string `json:"name"`
	NameNormalized string `json:"name_normalized"`
}

// Inserts a company if name_normalized doesn't exist yet, otherwise
// refreshes its display name and returns the existing id — callers always
// get an id to attach jobs to, never an error over "already exists".
func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCompany, arg.Name, arg.NameNormalized)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
