// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveJobs = `-- name: CountActiveJobs :one
SELECT count(*) FROM jobs WHERE is_active = TRUE AND canonical_job_id IS NULL
`

func (q *Queries) CountActiveJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deactivateStaleJobs = `-- name: DeactivateStaleJobs :execrows
UPDATE jobs
SET is_active = FALSE
WHERE is_active = TRUE
  AND last_seen_at < NOW() - ($1::int * INTERVAL '1 day')
`

func (q *Queries) DeactivateStaleJobs(ctx context.Context, staleAfterDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateStaleJobs, staleAfterDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findDuplicateCandidates = `-- name: FindDuplicateCandidates :many
SELECT id, title, title_normalized, company_id, description, salary_min, salary_max, salary_currency, salary_conf, salary_raw, stack, location, location_city, mode, level, source_id, source_url, source_job_id, fingerprint, canonical_job_id, search_vector, posted_at, first_seen_at, last_seen_at, is_active
FROM jobs
WHERE canonical_job_id IS NULL
  AND id != $1::uuid
  AND (
    fingerprint = $2::text
    OR (
      company_id = $3::uuid
      AND similarity(title_normalized, $4::text) > 0.7
    )
  )
ORDER BY posted_at ASC NULLS LAST, first_seen_at ASC
`

type FindDuplicateCandidatesParams struct {
	ExcludeJobID    uuid.UUID `json:"exclude_job_id"`
	Fingerprint     string    `json:"fingerprint"`
	CompanyID       uuid.UUID `json:"company_id"`
	TitleNormalized string    `json:"title_normalized"`
}

// Other canonical (not-yet-deduped) jobs that look like the same posting
// as the one identified by exclude_job_id: either an exact fingerprint
// match, or the same company with a fuzzy-matching title. The 0.7
// similarity threshold and what to do with the results is
// internal/store's call, not this query's — this just surfaces
// candidates, ordered oldest-first so the likely canonical sorts first.
func (q *Queries) FindDuplicateCandidates(ctx context.Context, arg FindDuplicateCandidatesParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, findDuplicateCandidates,
		arg.ExcludeJobID,
		arg.Fingerprint,
		arg.CompanyID,
		arg.TitleNormalized,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleNormalized,
			&i.CompanyID,
			&i.Description,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.SalaryConf,
			&i.SalaryRaw,
			&i.Stack,
			&i.Location,
			&i.LocationCity,
			&i.Mode,
			&i.Level,
			&i.SourceID,
			&i.SourceUrl,
			&i.SourceJobID,
			&i.Fingerprint,
			&i.CanonicalJobID,
			&i.SearchVector,
			&i.PostedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, title, title_normalized, company_id, description, salary_min, salary_max, salary_currency, salary_conf, salary_raw, stack, location, location_city, mode, level, source_id, source_url, source_job_id, fingerprint, canonical_job_id, search_vector, posted_at, first_seen_at, last_seen_at, is_active FROM jobs WHERE id = $1::uuid
`

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleNormalized,
		&i.CompanyID,
		&i.Description,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryConf,
		&i.SalaryRaw,
		&i.Stack,
		&i.Location,
		&i.LocationCity,
		&i.Mode,
		&i.Level,
		&i.SourceID,
		&i.SourceUrl,
		&i.SourceJobID,
		&i.Fingerprint,
		&i.CanonicalJobID,
		&i.SearchVector,
		&i.PostedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.IsActive,
	)
	return i, err
}

const listDuplicatesOf = `-- name: ListDuplicatesOf :many
SELECT id, title, title_normalized, company_id, description, salary_min, salary_max, salary_currency, salary_conf, salary_raw, stack, location, location_city, mode, level, source_id, source_url, source_job_id, fingerprint, canonical_job_id, search_vector, posted_at, first_seen_at, last_seen_at, is_active FROM jobs WHERE canonical_job_id = $1::uuid ORDER BY first_seen_at ASC
`

// Every duplicate of canonical_job_id, per our reparenting invariant
// (see ReparentDuplicates): always a flat one-level pointer, never a
// chain, so this alone is the complete set — no recursion needed.
func (q *Queries) ListDuplicatesOf(ctx context.Context, canonicalJobID uuid.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listDuplicatesOf, canonicalJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleNormalized,
			&i.CompanyID,
			&i.Description,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.SalaryConf,
			&i.SalaryRaw,
			&i.Stack,
			&i.Location,
			&i.LocationCity,
			&i.Mode,
			&i.Level,
			&i.SourceID,
			&i.SourceUrl,
			&i.SourceJobID,
			&i.Fingerprint,
			&i.CanonicalJobID,
			&i.SearchVector,
			&i.PostedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, title, title_normalized, company_id, description, salary_min, salary_max, salary_currency, salary_conf, salary_raw, stack, location, location_city, mode, level, source_id, source_url, source_job_id, fingerprint, canonical_job_id, search_vector, posted_at, first_seen_at, last_seen_at, is_active
FROM jobs
WHERE canonical_job_id IS NULL
  AND is_active = TRUE
  AND ($1::text[] IS NULL OR stack && $1::text[])
  -- "at least X" reads as "the job could pay at least X" (its upper
  -- bound clears the bar), not "its floor guarantees X" — the more
  -- permissive of the two reasonable readings, and what similar job
  -- boards do. Jobs with no known salary_max never match an active filter.
  AND ($2::bigint IS NULL OR salary_max >= $2::bigint)
  AND ($3::work_mode IS NULL OR mode = $3::work_mode)
  AND ($4::experience_level IS NULL OR level = $4::experience_level)
  AND ($5::text IS NULL OR location_city ILIKE $5::text)
  -- 'simple' must match the config the search_vector trigger indexes
  -- with (see migrations/001_init.sql) — querying with a different
  -- config's stemming/stopword rules would silently stop matching.
  AND ($6::text IS NULL OR search_vector @@ websearch_to_tsquery('simple', $6::text))
  AND (
    NOT $7::bool
    OR (COALESCE(posted_at, '-infinity'::timestamptz), id) <
       (COALESCE($8::timestamptz, '-infinity'::timestamptz), $9::uuid)
  )
ORDER BY COALESCE(posted_at, '-infinity'::timestamptz) DESC, id DESC
LIMIT $10::int
`

type ListJobsParams struct {
	Stack          []string            `json:"stack"`
	SalaryMin      pgtype.Int8         `json:"salary_min"`
	Mode           NullWorkMode        `json:"mode"`
	Level          NullExperienceLevel `json:"level"`
	City           pgtype.Text         `json:"city"`
	Query          pgtype.Text         `json:"query"`
	HasCursor      bool                `json:"has_cursor"`
	CursorPostedAt pgtype.Timestamptz  `json:"cursor_posted_at"`
	CursorID       pgtype.UUID         `json:"cursor_id"`
	PageLimit      int32               `json:"page_limit"`
}

// Keyset pagination on (posted_at, id), both descending — never OFFSET.
// has_cursor distinguishes "first page" from "page after a row whose own
// posted_at happens to be NULL"; overloading cursor_posted_at itself as
// that sentinel would conflate the two. NULL posted_at is treated as
// '-infinity' throughout (both here and in ORDER BY) so unknown-posted-
// date jobs consistently sort last instead of needing special-case
// handling in the keyset comparison.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.Stack,
		arg.SalaryMin,
		arg.Mode,
		arg.Level,
		arg.City,
		arg.Query,
		arg.HasCursor,
		arg.CursorPostedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleNormalized,
			&i.CompanyID,
			&i.Description,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.SalaryConf,
			&i.SalaryRaw,
			&i.Stack,
			&i.Location,
			&i.LocationCity,
			&i.Mode,
			&i.Level,
			&i.SourceID,
			&i.SourceUrl,
			&i.SourceJobID,
			&i.Fingerprint,
			&i.CanonicalJobID,
			&i.SearchVector,
			&i.PostedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsDuplicate = `-- name: MarkAsDuplicate :exec
UPDATE jobs
SET canonical_job_id = $1::uuid
WHERE id = $2::uuid
`

type MarkAsDuplicateParams struct {
	CanonicalJobID uuid.UUID `json:"canonical_job_id"`
	JobID          uuid.UUID `json:"job_id"`
}

func (q *Queries) MarkAsDuplicate(ctx context.Context, arg MarkAsDuplicateParams) error {
	_, err := q.db.Exec(ctx, markAsDuplicate, arg.CanonicalJobID, arg.JobID)
	return err
}

const reparentDuplicates = `-- name: ReparentDuplicates :exec
UPDATE jobs
SET canonical_job_id = $1::uuid
WHERE canonical_job_id = $2::uuid
`

type ReparentDuplicatesParams struct {
	NewCanonicalID uuid.UUID `json:"new_canonical_id"`
	OldCanonicalID uuid.UUID `json:"old_canonical_id"`
}

// When a merge displaces a previous canonical (an earlier-posted match
// for the same job surfaces later), anything already pointing at the
// demoted job needs to point straight at the new canonical instead —
// otherwise duplicates would form a two-level chain (dup -> old canonical
// -> new canonical) instead of every duplicate pointing directly at the
// true canonical.
func (q *Queries) ReparentDuplicates(ctx context.Context, arg ReparentDuplicatesParams) error {
	_, err := q.db.Exec(ctx, reparentDuplicates, arg.NewCanonicalID, arg.OldCanonicalID)
	return err
}

const stackStats = `-- name: StackStats :many
SELECT unnest(stack)::text AS stack, count(*) AS job_count
FROM jobs
WHERE is_active = TRUE AND canonical_job_id IS NULL
GROUP BY stack
ORDER BY job_count DESC, stack ASC
`

type StackStatsRow struct {
	Stack    string `json:"stack"`
	JobCount int64  `json:"job_count"`
}

// One row per technology across all active, canonical jobs, most common
// first. unnest() fans a job's stack array out into one row per element.
func (q *Queries) StackStats(ctx context.Context) ([]StackStatsRow, error) {
	rows, err := q.db.Query(ctx, stackStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StackStatsRow{}
	for rows.Next() {
		var i StackStatsRow
		if err := rows.Scan(&i.Stack, &i.JobCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJob = `-- name: UpsertJob :one
INSERT INTO jobs (
    title, title_normalized, company_id, description,
    salary_min, salary_max, salary_conf, salary_raw,
    stack, location, location_city, mode, level,
    source_id, source_url, source_job_id,
    fingerprint, posted_at
) VALUES (
    $1::text, $2::text, $3::uuid, $4::text,
    $5::bigint, $6::bigint, $7::salary_confidence, $8::text,
    $9::text[], $10::text, $11::text, $12::work_mode, $13::experience_level,
    $14::int, $15::text, $16::text,
    $17::text, $18::timestamptz
)
ON CONFLICT (source_id, source_url) DO UPDATE SET
    title             = EXCLUDED.title,
    title_normalized  = EXCLUDED.title_normalized,
    company_id        = EXCLUDED.company_id,
    description       = EXCLUDED.description,
    salary_min        = EXCLUDED.salary_min,
    salary_max        = EXCLUDED.salary_max,
    salary_conf       = EXCLUDED.salary_conf,
    salary_raw        = EXCLUDED.salary_raw,
    stack             = EXCLUDED.stack,
    location          = EXCLUDED.location,
    location_city     = EXCLUDED.location_city,
    mode              = EXCLUDED.mode,
    level             = EXCLUDED.level,
    source_job_id     = EXCLUDED.source_job_id,
    fingerprint       = EXCLUDED.fingerprint,
    posted_at         = EXCLUDED.posted_at,
    last_seen_at      = NOW(),
    is_active         = TRUE
RETURNING id, title, title_normalized, company_id, description, salary_min, salary_max, salary_currency, salary_conf, salary_raw, stack, location, location_city, mode, level, source_id, source_url, source_job_id, fingerprint, canonical_job_id, search_vector, posted_at, first_seen_at, last_seen_at, is_active
`

type UpsertJobParams struct {
	Title           string             `json:"title"`
	TitleNormalized string             `json:"title_normalized"`
	CompanyID       uuid.UUID          `json:"company_id"`
	Description     pgtype.Text        `json:"description"`
	SalaryMin       pgtype.Int8        `json:"salary_min"`
	SalaryMax       pgtype.Int8        `json:"salary_max"`
	SalaryConf      SalaryConfidence   `json:"salary_conf"`
	SalaryRaw       pgtype.Text        `json:"salary_raw"`
	Stack           []string           `json:"stack"`
	Location        pgtype.Text        `json:"location"`
	LocationCity    pgtype.Text        `json:"location_city"`
	Mode            WorkMode           `json:"mode"`
	Level           ExperienceLevel    `json:"level"`
	SourceID        int32              `json:"source_id"`
	SourceUrl       string             `json:"source_url"`
	SourceJobID     pgtype.Text        `json:"source_job_id"`
	Fingerprint     string             `json:"fingerprint"`
	PostedAt        pgtype.Timestamptz `json:"posted_at"`
}

// Inserts a job, or — keyed on (source_id, source_url), which is what a
// re-scrape of the same listing shares — refreshes its content and marks
// it seen again. canonical_job_id is deliberately absent from both the
// insert column list and the UPDATE SET: a re-scrape must never clobber a
// dedup decision already made for this row. salary_currency is absent
// too — our parser only ever produces IDR (or "unknown", which carries
// no currency at all), so there's nothing meaningful to write; the
// column's own DEFAULT 'IDR' covers the insert path, and an update
// simply leaves whatever is already there. Returns the full row (not
// just id): the store layer needs posted_at/first_seen_at/fingerprint/
// company_id/title_normalized right after upserting to run dedup
// resolution, and a second SELECT to fetch them would be redundant
// inside the same transaction.
func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, upsertJob,
		arg.Title,
		arg.TitleNormalized,
		arg.CompanyID,
		arg.Description,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryConf,
		arg.SalaryRaw,
		arg.Stack,
		arg.Location,
		arg.LocationCity,
		arg.Mode,
		arg.Level,
		arg.SourceID,
		arg.SourceUrl,
		arg.SourceJobID,
		arg.Fingerprint,
		arg.PostedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleNormalized,
		&i.CompanyID,
		&i.Description,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryConf,
		&i.SalaryRaw,
		&i.Stack,
		&i.Location,
		&i.LocationCity,
		&i.Mode,
		&i.Level,
		&i.SourceID,
		&i.SourceUrl,
		&i.SourceJobID,
		&i.Fingerprint,
		&i.CanonicalJobID,
		&i.SearchVector,
		&i.PostedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.IsActive,
	)
	return i, err
}
