// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExperienceLevel string

const (
	ExperienceLevelIntern  ExperienceLevel = "intern"
	ExperienceLevelJunior  ExperienceLevel = "junior"
	ExperienceLevelMid     ExperienceLevel = "mid"
	ExperienceLevelSenior  ExperienceLevel = "senior"
	ExperienceLevelLead    ExperienceLevel = "lead"
	ExperienceLevelUnknown ExperienceLevel = "unknown"
)

func (e *ExperienceLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExperienceLevel(s)
	case string:
		*e = ExperienceLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for ExperienceLevel: %T", src)
	}
	return nil
}

type NullExperienceLevel struct {
	ExperienceLevel ExperienceLevel `json:"experience_level"`
	Valid           bool            `json:"valid"` // Valid is true if ExperienceLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExperienceLevel) Scan(value interface{}) error {
	if value == nil {
		ns.ExperienceLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExperienceLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExperienceLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExperienceLevel), nil
}

type RunStatus string

const (
	RunStatusPending RunStatus = "pending"
	RunStatusRunning RunStatus = "running"
	RunStatusSuccess RunStatus = "success"
	RunStatusFailed  RunStatus = "failed"
)

func (e *RunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunStatus(s)
	case string:
		*e = RunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunStatus: %T", src)
	}
	return nil
}

type NullRunStatus struct {
	RunStatus RunStatus `json:"run_status"`
	Valid     bool      `json:"valid"` // Valid is true if RunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunStatus), nil
}

type SalaryConfidence string

const (
	SalaryConfidenceExact     SalaryConfidence = "exact"
	SalaryConfidenceRange     SalaryConfidence = "range"
	SalaryConfidenceEstimated SalaryConfidence = "estimated"
	SalaryConfidenceUnknown   SalaryConfidence = "unknown"
)

func (e *SalaryConfidence) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SalaryConfidence(s)
	case string:
		*e = SalaryConfidence(s)
	default:
		return fmt.Errorf("unsupported scan type for SalaryConfidence: %T", src)
	}
	return nil
}

type NullSalaryConfidence struct {
	SalaryConfidence SalaryConfidence `json:"salary_confidence"`
	Valid            bool             `json:"valid"` // Valid is true if SalaryConfidence is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSalaryConfidence) Scan(value interface{}) error {
	if value == nil {
		ns.SalaryConfidence, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SalaryConfidence.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSalaryConfidence) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SalaryConfidence), nil
}

type WorkMode string

const (
	WorkModeOnsite  WorkMode = "onsite"
	WorkModeRemote  WorkMode = "remote"
	WorkModeHybrid  WorkMode = "hybrid"
	WorkModeUnknown WorkMode = "unknown"
)

func (e *WorkMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkMode(s)
	case string:
		*e = WorkMode(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkMode: %T", src)
	}
	return nil
}

type NullWorkMode struct {
	WorkMode WorkMode `json:"work_mode"`
	Valid    bool     `json:"valid"` // Valid is true if WorkMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkMode) Scan(value interface{}) error {
	if value == nil {
		ns.WorkMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkMode), nil
}

type Alert struct {
	ID               uuid.UUID           `json:"id"`
	Email            string              `json:"email"`
	FilterStack      []string            `json:"filter_stack"`
	FilterSalaryMin  pgtype.Int8         `json:"filter_salary_min"`
	FilterMode       NullWorkMode        `json:"filter_mode"`
	FilterLevel      NullExperienceLevel `json:"filter_level"`
	FilterCity       pgtype.Text         `json:"filter_city"`
	IsVerified       bool                `json:"is_verified"`
	VerifyToken      pgtype.Text         `json:"verify_token"`
	UnsubscribeToken string              `json:"unsubscribe_token"`
	LastNotifiedAt   pgtype.Timestamptz  `json:"last_notified_at"`
	CreatedAt        pgtype.Timestamptz  `json:"created_at"`
}

type Company struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	NameNormalized string             `json:"name_normalized"`
	LogoUrl        pgtype.Text        `json:"logo_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID              uuid.UUID          `json:"id"`
	Title           string             `json:"title"`
	TitleNormalized string             `json:"title_normalized"`
	CompanyID       uuid.UUID          `json:"company_id"`
	Description     pgtype.Text        `json:"description"`
	SalaryMin       pgtype.Int8        `json:"salary_min"`
	SalaryMax       pgtype.Int8        `json:"salary_max"`
	SalaryCurrency  string             `json:"salary_currency"`
	SalaryConf      SalaryConfidence   `json:"salary_conf"`
	SalaryRaw       pgtype.Text        `json:"salary_raw"`
	Stack           []string           `json:"stack"`
	Location        pgtype.Text        `json:"location"`
	LocationCity    pgtype.Text        `json:"location_city"`
	Mode            WorkMode           `json:"mode"`
	Level           ExperienceLevel    `json:"level"`
	SourceID        int32              `json:"source_id"`
	SourceUrl       string             `json:"source_url"`
	SourceJobID     pgtype.Text        `json:"source_job_id"`
	Fingerprint     string             `json:"fingerprint"`
	CanonicalJobID  pgtype.UUID        `json:"canonical_job_id"`
	SearchVector    string             `json:"search_vector"`
	PostedAt        pgtype.Timestamptz `json:"posted_at"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	IsActive        bool               `json:"is_active"`
}

type ScrapeRun struct {
	ID            uuid.UUID          `json:"id"`
	SourceID      int32              `json:"source_id"`
	Status        RunStatus          `json:"status"`
	JobsFound     int32              `json:"jobs_found"`
	JobsNew       int32              `json:"jobs_new"`
	JobsDuplicate int32              `json:"jobs_duplicate"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type Source struct {
	ID        int32              `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	BaseUrl   string             `json:"base_url"`
	IsActive  bool               `json:"is_active"`
	LastRunAt pgtype.Timestamptz `json:"last_run_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
