// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountActiveJobs(ctx context.Context) (int64, error)
	// Starts a run: the two-function lifecycle (Create/Finish) means there's
	// no separate "pending" phase — by the time a run row is created, the
	// scraper is about to start immediately.
	CreateScrapeRun(ctx context.Context, sourceID int32) (uuid.UUID, error)
	DeactivateStaleJobs(ctx context.Context, staleAfterDays int32) (int64, error)
	// Other canonical (not-yet-deduped) jobs that look like the same posting
	// as the one identified by exclude_job_id: either an exact fingerprint
	// match, or the same company with a fuzzy-matching title. The 0.7
	// similarity threshold and what to do with the results is
	// internal/store's call, not this query's — this just surfaces
	// candidates, ordered oldest-first so the likely canonical sorts first.
	FindDuplicateCandidates(ctx context.Context, arg FindDuplicateCandidatesParams) ([]Job, error)
	FinishScrapeRun(ctx context.Context, arg FinishScrapeRunParams) error
	GetJobByID(ctx context.Context, id uuid.UUID) (Job, error)
	GetSourceBySlug(ctx context.Context, slug string) (Source, error)
	// Batch lookup for enriching a page of jobs with their company's display
	// name, e.g. in an HTTP handler — one query per page instead of one per
	// row.
	ListCompaniesByIDs(ctx context.Context, ids []uuid.UUID) ([]Company, error)
	// Every duplicate of canonical_job_id, per our reparenting invariant
	// (see ReparentDuplicates): always a flat one-level pointer, never a
	// chain, so this alone is the complete set — no recursion needed.
	ListDuplicatesOf(ctx context.Context, canonicalJobID uuid.UUID) ([]Job, error)
	// Keyset pagination on (posted_at, id), both descending — never OFFSET.
	// has_cursor distinguishes "first page" from "page after a row whose own
	// posted_at happens to be NULL"; overloading cursor_posted_at itself as
	// that sentinel would conflate the two. NULL posted_at is treated as
	// '-infinity' throughout (both here and in ORDER BY) so unknown-posted-
	// date jobs consistently sort last instead of needing special-case
	// handling in the keyset comparison.
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	MarkAsDuplicate(ctx context.Context, arg MarkAsDuplicateParams) error
	// When a merge displaces a previous canonical (an earlier-posted match
	// for the same job surfaces later), anything already pointing at the
	// demoted job needs to point straight at the new canonical instead —
	// otherwise duplicates would form a two-level chain (dup -> old canonical
	// -> new canonical) instead of every duplicate pointing directly at the
	// true canonical.
	ReparentDuplicates(ctx context.Context, arg ReparentDuplicatesParams) error
	// Per-source active job count (0 for a source with none, via LEFT JOIN)
	// plus when it was last scraped, for GET /api/stats.
	SourceStats(ctx context.Context) ([]SourceStatsRow, error)
	// One row per technology across all active, canonical jobs, most common
	// first. unnest() fans a job's stack array out into one row per element.
	// The unnest has to happen in a subquery: naming its output column "stack"
	// (matching the source jobs.stack array column) and then GROUP BY-ing that
	// same name in the *same* query scope makes Postgres resolve it back to
	// the original array column, not the unnested scalar — every job's whole
	// array is then its own group, so two different jobs that share a
	// technology never merge into one counted row (confirmed against a real
	// Postgres: with that shape, {Go,Docker} and {Go,Kubernetes} in two jobs
	// produced two separate "Go" rows, each count=1, instead of one row
	// count=2). A subquery puts the unnested column in its own scope, where
	// there's no longer a same-named array column for GROUP BY to prefer.
	StackStats(ctx context.Context) ([]StackStatsRow, error)
	UpdateSourceLastRunAt(ctx context.Context, id int32) error
	// Inserts a company if name_normalized doesn't exist yet, otherwise
	// refreshes its display name and returns the existing id — callers always
	// get an id to attach jobs to, never an error over "already exists".
	UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (uuid.UUID, error)
	// Inserts a job, or — keyed on (source_id, source_url), which is what a
	// re-scrape of the same listing shares — refreshes its content and marks
	// it seen again. canonical_job_id is deliberately absent from both the
	// insert column list and the UPDATE SET: a re-scrape must never clobber a
	// dedup decision already made for this row. salary_currency is absent
	// too — our parser only ever produces IDR (or "unknown", which carries
	// no currency at all), so there's nothing meaningful to write; the
	// column's own DEFAULT 'IDR' covers the insert path, and an update
	// simply leaves whatever is already there. Returns the full row (not
	// just id): the store layer needs posted_at/first_seen_at/fingerprint/
	// company_id/title_normalized right after upserting to run dedup
	// resolution, and a second SELECT to fetch them would be redundant
	// inside the same transaction.
	UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
