// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scrape_runs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScrapeRun = `-- name: CreateScrapeRun :one
INSERT INTO scrape_runs (source_id, status)
VALUES ($1::int, 'running')
RETURNING id
`

// Starts a run: the two-function lifecycle (Create/Finish) means there's
// no separate "pending" phase — by the time a run row is created, the
// scraper is about to start immediately.
func (q *Queries) CreateScrapeRun(ctx context.Context, sourceID int32) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createScrapeRun, sourceID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const finishScrapeRun = `-- name: FinishScrapeRun :exec
UPDATE scrape_runs
SET status         = $1::run_status,
    jobs_found     = $2::int,
    jobs_new       = $3::int,
    jobs_duplicate = $4::int,
    error_message  = $5::text,
    finished_at    = NOW()
WHERE id = $6::uuid
`

type FinishScrapeRunParams struct {
	Status        RunStatus   `json:"status"`
	JobsFound     int32       `json:"jobs_found"`
	JobsNew       int32       `json:"jobs_new"`
	JobsDuplicate int32       `json:"jobs_duplicate"`
	ErrorMessage  pgtype.Text `json:"error_message"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) FinishScrapeRun(ctx context.Context, arg FinishScrapeRunParams) error {
	_, err := q.db.Exec(ctx, finishScrapeRun,
		arg.Status,
		arg.JobsFound,
		arg.JobsNew,
		arg.JobsDuplicate,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
