// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSourceBySlug = `-- name: GetSourceBySlug :one
SELECT id, slug, name, base_url, is_active, last_run_at, created_at FROM sources WHERE slug = $1::text
`

func (q *Queries) GetSourceBySlug(ctx context.Context, slug string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceBySlug, slug)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BaseUrl,
		&i.IsActive,
		&i.LastRunAt,
		&i.CreatedAt,
	)
	return i, err
}

const sourceStats = `-- name: SourceStats :many
SELECT
    sources.id,
    sources.slug,
    sources.name,
    sources.last_run_at,
    COUNT(jobs.id) FILTER (WHERE jobs.is_active = TRUE AND jobs.canonical_job_id IS NULL) AS active_jobs
FROM sources
LEFT JOIN jobs ON jobs.source_id = sources.id
GROUP BY sources.id, sources.slug, sources.name, sources.last_run_at
ORDER BY sources.slug
`

type SourceStatsRow struct {
	ID         int32              `json:"id"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	ActiveJobs int64              `json:"active_jobs"`
}

// Per-source active job count (0 for a source with none, via LEFT JOIN)
// plus when it was last scraped, for GET /api/stats.
func (q *Queries) SourceStats(ctx context.Context) ([]SourceStatsRow, error) {
	rows, err := q.db.Query(ctx, sourceStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceStatsRow{}
	for rows.Next() {
		var i SourceStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.LastRunAt,
			&i.ActiveJobs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSourceLastRunAt = `-- name: UpdateSourceLastRunAt :exec
UPDATE sources SET last_run_at = NOW() WHERE id = $1::int
`

func (q *Queries) UpdateSourceLastRunAt(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateSourceLastRunAt, id)
	return err
}
